### ISSUE TITLE
Problems installing the custom nodes

### ISSUE THREAD

**Issue by FreezaSama** [TMElyralab/Comfyui-MusePose#1]
`When loading the graph, the following node types were not found:
filenamestring
museposealign
musepose
Nodes that have failed to load will show as red on the graph.`

Tried to install and uninstall, fix and whatnot via comfyui manager to no success, the nodes are still red

**Comment by fusillustrator** [comment]
same here

**Comment by lulu-xiao** [comment]
> `When loading the graph, the following node types were not found: filenamestring museposealign musepose Nodes that have failed to load will show as red on the graph.`
> 
> Tried to install and uninstall, fix and whatnot via comfyui manager to no success, the nodes are still red

Can you post the error message of the installation？

**Comment by lulu-xiao** [comment]
> same here

<img width="859" alt="企业微信截图_8ab886cd-06f6-4c3f-9af0-62ef553a86ae" src="https://github.com/TMElyralab/Comfyui-MusePose/assets/114042542/5ba1ee9a-7745-49b2-ae62-564601c03b8f">
try this？

**Comment by rethink-studios** [comment]
Yes, tried the above and here are the errors:

COMFY log:
Traceback (most recent call last):
  File "D:\COMFYUI_BETA\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\Comfyui-MusePose\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 30, in <module>
    from musepose.models.unet_2d_condition import UNet2DConditionModel
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\Comfyui-MusePose\musepose\models\unet_2d_condition.py", line 18, in <module>
    from diffusers.models.embeddings import (
ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings' (D:\COMFYUI_BETA\python_embeded\Lib\site-packages\diffusers\models\embeddings.py)

Cannot import D:\COMFYUI_BETA\ComfyUI\custom_nodes\Comfyui-MusePose module for custom nodes: cannot import name 'PositionNet' from 'diffusers.models.embeddings' (D:\COMFYUI_BETA\python_embeded\Lib\site-packages\diffusers\models\embeddings.py)
------------------------------------------


log:
![image](https://github.com/TMElyralab/Comfyui-MusePose/assets/60104539/5b759d70-be6d-4e73-8f1e-0d62df91c79c)


GUI:
![image](https://github.com/TMElyralab/Comfyui-MusePose/assets/60104539/627a9db8-320e-4266-9598-0a3a094abacf)


Any idea on how to fix?

Win11, python embedded..

Thanks!

**Comment by lulu-xiao** [comment]
> Yes, tried the above and here are the errors:
> 
> COMFY log: Traceback (most recent call last): File "D:\COMFYUI_BETA\ComfyUI\nodes.py", line 1879, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\Comfyui-MusePose__init__.py", line 1, in from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 30, in from musepose.models.unet_2d_condition import UNet2DConditionModel File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\Comfyui-MusePose\musepose\models\unet_2d_condition.py", line 18, in from diffusers.models.embeddings import ( ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings' (D:\COMFYUI_BETA\python_embeded\Lib\site-packages\diffusers\models\embeddings.py)
> 
> ## Cannot import D:\COMFYUI_BETA\ComfyUI\custom_nodes\Comfyui-MusePose module for custom nodes: cannot import name 'PositionNet' from 'diffusers.models.embeddings' (D:\COMFYUI_BETA\python_embeded\Lib\site-packages\diffusers\models\embeddings.py)
> log: ![image](https://private-user-images.githubusercontent.com/60104539/335810269-5b759d70-be6d-4e73-8f1e-0d62df91c79c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyOTUwOTEsIm5iZiI6MTcxNzI5NDc5MSwicGF0aCI6Ii82MDEwNDUzOS8zMzU4MTAyNjktNWI3NTlkNzAtYmU2ZC00ZTczLThmMWUtMGQ2MmRmOTFjNzljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDAyMTk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMjBjOTA1ZmI0NDRjYjVlZDFhMjY2MWMyNDA1OTM1YWQ3NTc0MTRkZjVkY2Q4NmI2MzQ3ZWZmMDVlZjI0NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bArRuzliEBVGH-byFakeH6P7gOSQQ4gvJ5ng96ot6_U)
> 
> GUI: ![image](https://private-user-images.githubusercontent.com/60104539/335810288-627a9db8-320e-4266-9598-0a3a094abacf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyOTUwOTEsIm5iZiI6MTcxNzI5NDc5MSwicGF0aCI6Ii82MDEwNDUzOS8zMzU4MTAyODgtNjI3YTlkYjgtMzIwZS00MjY2LTk1OTgtMGEzYTA5NGFiYWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDAyMTk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2OWE2YzkxNzI0NWQwMjc0NDFmZGVlMmYzOGQwMTlhN2U5M2FiZTQ2MDBiN2M3ZTJmMWJmY2IzMjY4MzY5YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jAq9UowPQ1slSgDFDv8yKh5PbqYLDjbVeKnZbLj2g2Q)
> 
> Any idea on how to fix?
> 
> Win11, python embedded..
> 
> Thanks!

requirement.txt is updated, you can try it again

**Comment by rethink-studios** [comment]
Thanks for the update!!

The error I get now is in the muse_pose_align node:

![image](https://github.com/TMElyralab/Comfyui-MusePose/assets/60104539/df9c0697-c7ef-41e2-8398-2e6d8a32195e)




Error occurred when executing museposealign:

name 'init_detector' is not defined

File "D:\COMFYUI_BETA\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\COMFYUI_BETA\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\COMFYUI_BETA\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 554, in posealign_func
return run_align_video_with_filterPose_translate_smooth(args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 276, in run_align_video_with_filterPose_translate_smooth
detector = DWposeDetector(
^^^^^^^^^^^^^^^
File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\Comfyui-MusePose\pose\script\dwpose.py", line 74, in __init__
self.pose_estimation = Wholebody(det_config, det_ckpt, pose_config, pose_ckpt, device)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\Comfyui-MusePose\pose\script\wholebody.py", line 51, in __init__
self.detector = init_detector(det_config, det_ckpt, device=device)
^^^^^^^^^^^^^

**Comment by Tophness** [comment]
[Solution](https://github.com/TMElyralab/Comfyui-MusePose/issues/26) @ #26
