### ISSUE TITLE
ValueError: not allowed to raise maximum limit

### ISSUE THREAD

**Issue by karthikg-09** [TMElyralab/Comfyui-MusePose#10]
I am getting the following error

```got prompt
Param(yolox_config='/workspace/ComfyUI/custom_nodes/Comfyui-MusePose/pose/config/yolox_l_8xb8-300e_coco.py', dwpose_config='/workspace/ComfyUI/custom_nodes/Comfyui-MusePose/pose/config/dwpose-l_384x288.py', yolox_ckpt='/workspace/ComfyUI/custom_nodes/Comfyui-MusePose/pretrained_weights/dwpose/yolox_l_8x8_300e_coco.pth', dwpose_ckpt='/workspace/ComfyUI/custom_nodes/Comfyui-MusePose/pretrained_weights/dwpose/dw-ll_ucoco_384.pth', outfn_align_pose_video=None, outfn=None, detect_resolution=640, image_resolution=640, align_frame=0, max_frame=300, imgfn_refer='/workspace/ComfyUI/custom_nodes/Comfyui-MusePose/data/ref_image.jpg', vidfn='/workspace/ComfyUI/temp/AnimateDiff_00003.mp4')
height: 854.0
width: 480.0
fps: 24.0
!!! Exception during processing!!! not allowed to raise maximum limit
Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/workspace/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/workspace/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/workspace/ComfyUI/custom_nodes/Comfyui-MusePose/nodes.py", line 554, in posealign_func
    return run_align_video_with_filterPose_translate_smooth(args)
  File "/workspace/ComfyUI/custom_nodes/Comfyui-MusePose/nodes.py", line 276, in run_align_video_with_filterPose_translate_smooth
    detector = DWposeDetector(
  File "/workspace/ComfyUI/custom_nodes/Comfyui-MusePose/pose/script/dwpose.py", line 72, in __init__
    from pose.script.wholebody import Wholebody
  File "/workspace/ComfyUI/custom_nodes/Comfyui-MusePose/pose/script/wholebody.py", line 14, in <module>
    from mmpose.apis import inference_topdown
  File "/workspace/ComfyUI/venv/lib/python3.10/site-packages/mmpose/apis/__init__.py", line 2, in <module>
    from .inference import (collect_multi_frames, inference_bottomup,
  File "/workspace/ComfyUI/venv/lib/python3.10/site-packages/mmpose/apis/inference.py", line 16, in <module>
    from mmpose.datasets.datasets.utils import parse_pose_metainfo
  File "/workspace/ComfyUI/venv/lib/python3.10/site-packages/mmpose/datasets/__init__.py", line 2, in <module>
    from .builder import build_dataset
  File "/workspace/ComfyUI/venv/lib/python3.10/site-packages/mmpose/datasets/builder.py", line 20, in <module>
    resource.setrlimit(resource.RLIMIT_NOFILE, (soft_limit, hard_limit))
ValueError: not allowed to raise maximum limit

Prompt executed in 1.80 seconds

**Comment by RONNYKHALIL** [comment]
+1

**Comment by dedkamaroz** [comment]
+1

**Comment by cleexiang** [comment]
+1

**Comment by WanderGink** [comment]
+1

**Comment by yzcaimz** [comment]
+1
