### ISSUE TITLE
NameError: name 'init_detector' is not defined

### ISSUE THREAD

**Issue by gstocker75** [TMElyralab/Comfyui-MusePose#11]
On first install i was getting the 
NameError: name 'adapt_mmdet_pipeline' is not defined
error. 
i proceeded to update comfy(didn't help), then did update comfy and python dependencies.  that solved the adapt_mmdet error. 
now i'm getting this 'init_detector' is not defined error.  

full log of my session. 

```
## ComfyUI-Manager: installing dependencies done.
[2024-06-02 01:35] ** ComfyUI startup time: 2024-06-02 01:35:58.712475
[2024-06-02 01:35] ** Platform: Windows
[2024-06-02 01:35] ** Python version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
[2024-06-02 01:35] ** Python executable: D:\AI\ComfyUI_windows_portable\python_embeded\python.exe
[2024-06-02 01:35] ** Log path: D:\AI\ComfyUI_windows_portable\comfyui.log
[2024-06-02 01:35] 
Prestartup times for custom nodes:
[2024-06-02 01:35]    0.2 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-06-02 01:35] 
Total VRAM 24564 MB, total RAM 65382 MB
[2024-06-02 01:35] pytorch version: 2.3.0+cu118
[2024-06-02 01:36] xformers version: 0.0.26.post1+cu118
[2024-06-02 01:36] Set vram state to: NORMAL_VRAM
[2024-06-02 01:36] Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
[2024-06-02 01:36] VAE dtype: torch.bfloat16
[2024-06-02 01:36] Using xformers cross attention
[2024-06-02 01:36] Adding extra search path checkpoints D:\AI\stable-diffusion-webui\models/Stable-diffusion
[2024-06-02 01:36] Adding extra search path configs D:\AI\stable-diffusion-webui\models/Stable-diffusion
[2024-06-02 01:36] Adding extra search path vae D:\AI\stable-diffusion-webui\models/VAE
[2024-06-02 01:36] Adding extra search path loras D:\AI\stable-diffusion-webui\models/Lora
[2024-06-02 01:36] Adding extra search path upscale_models D:\AI\stable-diffusion-webui\models/ESRGAN
[2024-06-02 01:36] Adding extra search path upscale_models D:\AI\stable-diffusion-webui\models/SwinIR
[2024-06-02 01:36] Adding extra search path embeddings D:\AI\stable-diffusion-webui\embeddings
[2024-06-02 01:36] Adding extra search path hypernetworks D:\AI\stable-diffusion-webui\models/hypernetworks
[2024-06-02 01:36] Adding extra search path controlnet D:\AI\stable-diffusion-webui\models/ControlNet
[2024-06-02 01:36] Adding extra search path clip D:\AI\stable-diffusion-webui\models/clip/
[2024-06-02 01:36] Adding extra search path clip_vision D:\AI\stable-diffusion-webui\models/clip_vision/
[2024-06-02 01:36] Adding extra search path ipadapter D:\AI\stable-diffusion-webui\models/IP-Adapter
[2024-06-02 01:36] [Crystools [0;32mINFO[0m] Crystools version: 1.12.0
[2024-06-02 01:36] [Crystools [0;32mINFO[0m] CPU: 13th Gen Intel(R) Core(TM) i9-13900KF - Arch: AMD64 - OS: Windows 10
[2024-06-02 01:36] [Crystools [0;32mINFO[0m] GPU/s:
[2024-06-02 01:36] [Crystools [0;32mINFO[0m] 0) NVIDIA GeForce RTX 4090
[2024-06-02 01:36] [Crystools [0;32mINFO[0m] NVIDIA Driver: 546.33
[2024-06-02 01:36] Total VRAM 24564 MB, total RAM 65382 MB
[2024-06-02 01:36] pytorch version: 2.3.0+cu118
[2024-06-02 01:36] xformers version: 0.0.26.post1+cu118
[2024-06-02 01:36] Set vram state to: NORMAL_VRAM
[2024-06-02 01:36] Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
[2024-06-02 01:36] VAE dtype: torch.bfloat16
[2024-06-02 01:36] ### Loading: ComfyUI-Manager (V2.36)
[2024-06-02 01:36] ### ComfyUI Revision: 2221 [b2498620] | Released on '2024-06-01'
[2024-06-02 01:36] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2024-06-02 01:36] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2024-06-02 01:36] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-06-02 01:36] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2024-06-02 01:36] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[2024-06-02 01:36] D:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\models\dual_transformer_2d.py:20: FutureWarning: `DualTransformer2DModel` is deprecated and will be removed in version 0.29. Importing `DualTransformer2DModel` from `diffusers.models.dual_transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.transformers.dual_transformer_2d import DualTransformer2DModel`, instead.
  deprecate("DualTransformer2DModel", "0.29", deprecation_message)
[2024-06-02 01:36] (pysssss:WD14Tagger) [DEBUG] Available ORT providers: CPUExecutionProvider
[2024-06-02 01:36] (pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
[2024-06-02 01:36] [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m
[2024-06-02 01:36] [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
[2024-06-02 01:36] [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
[2024-06-02 01:36] D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
[2024-06-02 01:36] Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-06-02 01:36] NumExpr defaulting to 8 threads.
[2024-06-02 01:36] [34mFizzleDorf Custom Nodes: [92mLoaded[0m
[2024-06-02 01:36] Searge-SDXL v4.3.1 in D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
[2024-06-02 01:36] [34mWAS Node Suite: [0mOpenCV Python FFMPEG support is enabled[0m
[2024-06-02 01:36] [34mWAS Node Suite [93mWarning: [0m`ffmpeg_bin_path` is not set in `D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.[0m
[2024-06-02 01:36] [34mWAS Node Suite: [0mFinished.[0m [32mLoaded[0m [0m212[0m [32mnodes successfully.[0m
[2024-06-02 01:36] 
	[3m[93m"Art is not what you see, but what you make others see."[0m[3m - Edgar Degas[0m
[2024-06-02 01:36] 
[2024-06-02 01:36] 
Import times for custom nodes:
[2024-06-02 01:36]    0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\SDXLAspectRatio.py
[2024-06-02 01:36]    0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\fcSuite.py
[2024-06-02 01:36]    0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
[2024-06-02 01:36]    0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Mile_High_Styler
[2024-06-02 01:36]    0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
[2024-06-02 01:36]    0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
[2024-06-02 01:36]    0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\mikey_nodes
[2024-06-02 01:36]    0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-various
[2024-06-02 01:36]    0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
[2024-06-02 01:36]    0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
[2024-06-02 01:36]    0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
[2024-06-02 01:36]    0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
[2024-06-02 01:36]    0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
[2024-06-02 01:36]    0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
[2024-06-02 01:36]    0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
[2024-06-02 01:36]    0.1 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
[2024-06-02 01:36]    0.1 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
[2024-06-02 01:36]    0.1 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
[2024-06-02 01:36]    0.2 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
[2024-06-02 01:36]    0.2 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-06-02 01:36]    0.2 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose
[2024-06-02 01:36]    0.2 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
[2024-06-02 01:36]    0.6 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR
[2024-06-02 01:36]    0.9 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
[2024-06-02 01:36]    2.7 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
[2024-06-02 01:36] 
[2024-06-02 01:36] Starting server

[2024-06-02 01:36] To see the GUI go to: http://127.0.0.1:8188
[2024-06-02 01:36] FETCH DATA from: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[2024-06-02 01:36] got prompt
[2024-06-02 01:36] Param(yolox_config='D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\Comfyui-MusePose\\pose/config/yolox_l_8xb8-300e_coco.py', dwpose_config='D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\Comfyui-MusePose\\pose/config/dwpose-l_384x288.py', yolox_ckpt='D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\Comfyui-MusePose\\pretrained_weights/dwpose/yolox_l_8x8_300e_coco.pth', dwpose_ckpt='D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\Comfyui-MusePose\\pretrained_weights/dwpose/dw-ll_ucoco_384.pth', outfn_align_pose_video=None, outfn=None, detect_resolution=512, image_resolution=700, align_frame=0, max_frame=300, imgfn_refer='D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\Comfyui-MusePose\\data/ref_image.jpg', vidfn='D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\temp\\AnimateDiff_00001.mp4')
[2024-06-02 01:36] height: 512.0
[2024-06-02 01:36] width: 512.0
[2024-06-02 01:36] fps: 24.0
[2024-06-02 01:36] !!! Exception during processing!!! name 'init_detector' is not defined
[2024-06-02 01:36] Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 554, in posealign_func
    return run_align_video_with_filterPose_translate_smooth(args)
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 276, in run_align_video_with_filterPose_translate_smooth
    detector = DWposeDetector(
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose\pose\script\dwpose.py", line 74, in __init__
    self.pose_estimation = Wholebody(det_config, det_ckpt, pose_config, pose_ckpt, device)
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose\pose\script\wholebody.py", line 52, in __init__
    self.detector = init_detector(det_config, det_ckpt, device=device)
NameError: name 'init_detector' is not defined

[2024-06-02 01:36] Prompt executed in 2.13 seconds
```

**Comment by ManuelMultiverse** [comment]
Same issue here.

**Comment by gstocker75** [comment]
just saw this is a duplicate.  closing
