### ISSUE TITLE
Can't install requirements (openmim) on Windows

### ISSUE THREAD

**Issue by Tophness** [TMElyralab/Comfyui-MusePose#13]
```
E:\Downloads\ComfyUI\ComfyUI\custom_nodes\Comfyui-MusePose>..\..\..\python_embeded\python.exe -s -m pip install --no-cache-dir -U openmim
Collecting openmim
  Downloading openmim-0.3.9-py2.py3-none-any.whl.metadata (16 kB)
Collecting Click (from openmim)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: colorama in e:\downloads\comfyui\python_embeded\lib\site-packages (from openmim) (0.4.6)
Collecting model-index (from openmim)
  Downloading model_index-0.1.11-py3-none-any.whl.metadata (3.9 kB)
Collecting opendatalab (from openmim)
  Downloading opendatalab-0.0.10-py3-none-any.whl.metadata (6.4 kB)
Collecting pandas (from openmim)
  Downloading pandas-2.2.2-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: pip>=19.3 in e:\downloads\comfyui\python_embeded\lib\site-packages (from openmim) (24.0)
Requirement already satisfied: requests in e:\downloads\comfyui\python_embeded\lib\site-packages (from openmim) (2.31.0)
Collecting rich (from openmim)
  Downloading rich-13.7.1-py3-none-any.whl.metadata (18 kB)
Collecting tabulate (from openmim)
  Downloading tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: pyyaml in e:\downloads\comfyui\python_embeded\lib\site-packages (from model-index->openmim) (6.0.1)
Collecting markdown (from model-index->openmim)
  Downloading Markdown-3.6-py3-none-any.whl.metadata (7.0 kB)
Collecting ordered-set (from model-index->openmim)
  Downloading ordered_set-4.1.0-py3-none-any.whl.metadata (5.3 kB)
Collecting pycryptodome (from opendatalab->openmim)
  Downloading pycryptodome-3.20.0-cp35-abi3-win_amd64.whl.metadata (3.4 kB)
Requirement already satisfied: tqdm in e:\downloads\comfyui\python_embeded\lib\site-packages (from opendatalab->openmim) (4.66.4)
Collecting openxlab (from opendatalab->openmim)
  Downloading openxlab-0.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting pywin32 (from opendatalab->openmim)
  Downloading pywin32-306-cp311-cp311-win_amd64.whl.metadata (6.5 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\downloads\comfyui\python_embeded\lib\site-packages (from requests->openmim) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in e:\downloads\comfyui\python_embeded\lib\site-packages (from requests->openmim) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\downloads\comfyui\python_embeded\lib\site-packages (from requests->openmim) (1.26.9)
Requirement already satisfied: certifi>=2017.4.17 in e:\downloads\comfyui\python_embeded\lib\site-packages (from requests->openmim) (2023.5.7)
Requirement already satisfied: numpy>=1.23.2 in e:\downloads\comfyui\python_embeded\lib\site-packages (from pandas->openmim) (1.25.0)
Collecting python-dateutil>=2.8.2 (from pandas->openmim)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas->openmim)
  Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas->openmim)
  Downloading tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting markdown-it-py>=2.2.0 (from rich->openmim)
  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich->openmim)
  Downloading pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->openmim)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->openmim)
  Downloading six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting filelock~=3.14.0 (from openxlab->opendatalab->openmim)
  Downloading filelock-3.14.0-py3-none-any.whl.metadata (2.8 kB)
Collecting oss2~=2.17.0 (from openxlab->opendatalab->openmim)
  Downloading oss2-2.17.0.tar.gz (259 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.5/259.5 kB 5.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting packaging~=24.0 (from openxlab->opendatalab->openmim)
  Downloading packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
Collecting pytz>=2020.1 (from pandas->openmim)
  Downloading pytz-2023.4-py2.py3-none-any.whl.metadata (22 kB)
Collecting requests (from openmim)
  Downloading requests-2.28.2-py3-none-any.whl.metadata (4.6 kB)
Collecting rich (from openmim)
  Downloading rich-13.4.2-py3-none-any.whl.metadata (18 kB)
Collecting setuptools~=60.2.0 (from openxlab->opendatalab->openmim)
  Downloading setuptools-60.2.0-py3-none-any.whl.metadata (5.1 kB)
Collecting tqdm (from opendatalab->openmim)
  Downloading tqdm-4.65.2-py3-none-any.whl.metadata (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 kB ? eta 0:00:00
Collecting crcmod>=1.7 (from oss2~=2.17.0->openxlab->opendatalab->openmim)
  Downloading crcmod-1.7.tar.gz (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.7/89.7 kB ? eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting aliyun-python-sdk-kms>=2.4.1 (from oss2~=2.17.0->openxlab->opendatalab->openmim)
  Downloading aliyun_python_sdk_kms-2.16.3-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting aliyun-python-sdk-core>=2.13.12 (from oss2~=2.17.0->openxlab->opendatalab->openmim)
  Downloading aliyun-python-sdk-core-2.15.1.tar.gz (443 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 443.1/443.1 kB 9.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\chris\AppData\Local\Temp\pip-install-41xx2qx9\aliyun-python-sdk-core_4f6c57c5dde1447588ebd986dc396e58\setup.py", line 41, in <module>
          VERSION = __import__(PACKAGE).__version__
                    ^^^^^^^^^^^^^^^^^^^
      ModuleNotFoundError: No module named 'aliyunsdkcore'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

If I try installing aliyunsdkcore separately I get the same error:

```
E:\Downloads\ComfyUI\ComfyUI\custom_nodes\Comfyui-MusePose>..\..\..\python_embeded\python.exe -s -m pip install aliyunsdkcore
Collecting aliyunsdkcore
  Downloading aliyunsdkcore-1.0.3.tar.gz (23 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\chris\AppData\Local\Temp\pip-install-hp4i2h59\aliyunsdkcore_8152039ce0fc43d1b64736f8d68dc615\setup.py", line 225, in <module>
          VERSION = __import__(PACKAGE).__version__
                    ^^^^^^^^^^^^^^^^^^^
      ModuleNotFoundError: No module named 'aliyunsdkcore'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by huiyichanmian** [comment]
Same issue here.
I want to know if you have solved this problem? If it is resolved, how was it resolved?

**Comment by fusillustrator** [comment]
same

**Comment by Tophness** [comment]
Fixed with `pip install aliyun-python-sdk-core-v3==2.13.10` (old version that only works because it has a pre-built wheel for windows)

**Comment by huiyichanmian** [comment]
I successfully installed it using Python. exe - m pip install aliyun-python-sdk-core-v3==2.13.10. 
I also used the command to install openmim, but when executing mim, the system prompted that it was not an internal or external command.

**Comment by fusillustrator** [comment]
huh how did u guys fiux?

**Comment by fusillustrator** [comment]
> Fixed with `pip install aliyun-python-sdk-core-v3==2.13.10` (old version that only works because it has a pre-built wheel for windows)

> I successfully installed it using Python. exe - m pip install aliyun-python-sdk-core-v3==2.13.10. I also used the command to install openmim, but when executing mim, the system prompted that it was not an internal or external command.

what did you do? I put same command but it didnot install

**Comment by huiyichanmian** [comment]
> 我使用python exe -m pip install aliyun-python-sdk-core-v3==2.13.10安装成功， 也使用命令安装过openmim，但是执行mim的时候系统提示不是内部或外部命令。

这个是我自己的问题， 使用mim时候，前面还是需要加上python.exe -m。

**Comment by lulu-xiao** [comment]
is this tutorial helpful？
https://www.bilibili.com/video/BV1kM4m1z7Tq/?spm_id_from=333.337.search-card.all.click

**Comment by ManuelMultiverse** [comment]
do you have any eng video?

**Comment by Tophness** [comment]
[Solution](https://github.com/TMElyralab/Comfyui-MusePose/issues/26) @ #26
