### ISSUE TITLE
mmpose doesnot install, it keeps failing to build wheel

### ISSUE THREAD

**Issue by fusillustrator** [TMElyralab/Comfyui-MusePose#15]
PS D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose> pip install mmpose
Collecting mmpose
  Using cached mmpose-1.3.1-py2.py3-none-any.whl.metadata (29 kB)
Collecting chumpy (from mmpose)
  Using cached chumpy-0.70.tar.gz (50 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "<string>", line 9, in <module>
      ModuleNotFoundError: No module named 'pip'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\fatbi\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\fatbi\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\fatbi\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\fatbi\AppData\Local\Temp\pip-build-env-_7rxsme6\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\fatbi\AppData\Local\Temp\pip-build-env-_7rxsme6\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\fatbi\AppData\Local\Temp\pip-build-env-_7rxsme6\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\fatbi\AppData\Local\Temp\pip-build-env-_7rxsme6\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
      ModuleNotFoundError: No module named 'pip'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose>

**Comment by marcusaureliusfun** [comment]
Also experiencing this

**Comment by ManuelMultiverse** [comment]
same here, not installing

**Comment by lulu-xiao** [comment]
> PS D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose> pip install mmpose Collecting mmpose Using cached mmpose-1.3.1-py2.py3-none-any.whl.metadata (29 kB) Collecting chumpy (from mmpose) Using cached chumpy-0.70.tar.gz (50 kB) Installing build dependencies ... done Getting requirements to build wheel ... error error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [23 lines of output] Traceback (most recent call last): File "", line 9, in ModuleNotFoundError: No module named 'pip'
> 
> ```
>   During handling of the above exception, another exception occurred:
> 
>   Traceback (most recent call last):
>     File "C:\Users\fatbi\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
>       main()
>     File "C:\Users\fatbi\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
>       json_out['return_val'] = hook(**hook_input['kwargs'])
>     File "C:\Users\fatbi\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
>       return hook(config_settings)
>     File "C:\Users\fatbi\AppData\Local\Temp\pip-build-env-_7rxsme6\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
>       return self._get_build_requires(config_settings, requirements=['wheel'])
>     File "C:\Users\fatbi\AppData\Local\Temp\pip-build-env-_7rxsme6\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
>       self.run_setup()
>     File "C:\Users\fatbi\AppData\Local\Temp\pip-build-env-_7rxsme6\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
>       super().run_setup(setup_script=setup_script)
>     File "C:\Users\fatbi\AppData\Local\Temp\pip-build-env-_7rxsme6\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
>       exec(code, locals())
>     File "<string>", line 11, in <module>
>   ModuleNotFoundError: No module named 'pip'
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. PS D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose>

this tutorial may help
https://www.bilibili.com/video/BV1kM4m1z7Tq/?spm_id_from=333.337.search-card.all.click

**Comment by fusillustrator** [comment]
update i fixed it by pip build wheel

**Comment by bparrott78** [comment]
> > PS D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose> pip install mmpose Collecting mmpose Using cached mmpose-1.3.1-py2.py3-none-any.whl.metadata (29 kB) Collecting chumpy (from mmpose) Using cached chumpy-0.70.tar.gz (50 kB) Installing build dependencies ... done Getting requirements to build wheel ... error error: subprocess-exited-with-error
> > × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [23 lines of output] Traceback (most recent call last): File "", line 9, in ModuleNotFoundError: No module named 'pip'
> > ```
> >   During handling of the above exception, another exception occurred:
> > 
> >   Traceback (most recent call last):
> >     File "C:\Users\fatbi\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
> >       main()
> >     File "C:\Users\fatbi\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
> >       json_out['return_val'] = hook(**hook_input['kwargs'])
> >     File "C:\Users\fatbi\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
> >       return hook(config_settings)
> >     File "C:\Users\fatbi\AppData\Local\Temp\pip-build-env-_7rxsme6\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
> >       return self._get_build_requires(config_settings, requirements=['wheel'])
> >     File "C:\Users\fatbi\AppData\Local\Temp\pip-build-env-_7rxsme6\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
> >       self.run_setup()
> >     File "C:\Users\fatbi\AppData\Local\Temp\pip-build-env-_7rxsme6\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
> >       super().run_setup(setup_script=setup_script)
> >     File "C:\Users\fatbi\AppData\Local\Temp\pip-build-env-_7rxsme6\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
> >       exec(code, locals())
> >     File "<string>", line 11, in <module>
> >   ModuleNotFoundError: No module named 'pip'
> >   [end of output]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> > × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output.
> > note: This error originates from a subprocess, and is likely not a problem with pip. PS D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose>
> 
> this tutorial may help https://www.bilibili.com/video/BV1kM4m1z7Tq/?spm_id_from=333.337.search-card.all.click

Is there perhaps an english source for this?  I have no idea what's happening here.

**Comment by lulu-xiao** [comment]
> > > PS D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose> pip install mmpose Collecting mmpose Using cached mmpose-1.3.1-py2.py3-none-any.whl.metadata (29 kB) Collecting chumpy (from mmpose) Using cached chumpy-0.70.tar.gz (50 kB) Installing build dependencies ... done Getting requirements to build wheel ... error error: subprocess-exited-with-error
> > > × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [23 lines of output] Traceback (most recent call last): File "", line 9, in ModuleNotFoundError: No module named 'pip'
> > > ```
> > >   During handling of the above exception, another exception occurred:
> > > 
> > >   Traceback (most recent call last):
> > >     File "C:\Users\fatbi\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
> > >       main()
> > >     File "C:\Users\fatbi\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
> > >       json_out['return_val'] = hook(**hook_input['kwargs'])
> > >     File "C:\Users\fatbi\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
> > >       return hook(config_settings)
> > >     File "C:\Users\fatbi\AppData\Local\Temp\pip-build-env-_7rxsme6\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
> > >       return self._get_build_requires(config_settings, requirements=['wheel'])
> > >     File "C:\Users\fatbi\AppData\Local\Temp\pip-build-env-_7rxsme6\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
> > >       self.run_setup()
> > >     File "C:\Users\fatbi\AppData\Local\Temp\pip-build-env-_7rxsme6\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
> > >       super().run_setup(setup_script=setup_script)
> > >     File "C:\Users\fatbi\AppData\Local\Temp\pip-build-env-_7rxsme6\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
> > >       exec(code, locals())
> > >     File "<string>", line 11, in <module>
> > >   ModuleNotFoundError: No module named 'pip'
> > >   [end of output]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> > > × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output.
> > > note: This error originates from a subprocess, and is likely not a problem with pip. PS D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose>
> > 
> > 
> > this tutorial may help https://www.bilibili.com/video/BV1kM4m1z7Tq/?spm_id_from=333.337.search-card.all.click
> 
> Is there perhaps an english source for this? I have no idea what's happening here.

using "\python_embeded\python -m pip install xxxx? "

**Comment by doogyhatts** [comment]
I couldn't install mmpose.

> Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "C:\tools\StabilityMatrix\Packages\ComfyUI (MusePose)\venv\lib\site-packages\setuptools\__init__.py", line 8, in <module>
          import _distutils_hack.override  # noqa: F401
        File "C:\tools\StabilityMatrix\Packages\ComfyUI (MusePose)\venv\lib\site-packages\_distutils_hack\override.py", line 1, in <module>
          __import__('_distutils_hack').do_override()
        File "C:\tools\StabilityMatrix\Packages\ComfyUI (MusePose)\venv\lib\site-packages\_distutils_hack\__init__.py", line 73, in do_override
          ensure_local_distutils()
        File "C:\tools\StabilityMatrix\Packages\ComfyUI (MusePose)\venv\lib\site-packages\_distutils_hack\__init__.py", line 61, in ensure_local_distutils
          assert '_distutils' in core.__file__, core.__file__
      AssertionError: C:\tools\StabilityMatrix\Packages\ComfyUI (MusePose)\venv\Scripts\python310.zip\distutils\core.pyc
      [end of output]

**Comment by FayeValentineSSS** [comment]
ok bro,you just need this: pip install wheel
When you "pip installed wheel", everything is fine
![微信截图_20240619110833](https://github.com/TMElyralab/Comfyui-MusePose/assets/129222806/04978c77-279e-47bf-9dab-991d0d417c42)

**Comment by xiaowuzicode** [comment]
ok bro, you just need this: pip install wheel When you "pip installed wheel", everything is fine ![微信截图_20240619110833](https://private-user-images.githubusercontent.com/129222806/340899280-04978c77-279e-47bf-9dab-991d0d417c42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODE1NzgsIm5iZiI6MTcxODc4MTI3OCwicGF0aCI6Ii8xMjkyMjI4MDYvMzQwODk5MjgwLTA0OTc4Yzc3LTI3OWUtNDdiZi05ZGFiLTk5MWQwZDQxN2M0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwNzE0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWI3ZDU0MDIxODk0NmI3OTA4NjliNDc1ZGIxM2M5MTYzMWRhNWNkYjJkY2Q4NzYwNThjZjljMDc2NmY2ZGMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0wcXG4Gq99PfwRhmXpjYAPcO2JRS9veJ_mUiseXvxCc)

You're awesome, solved, thank you!
