### ISSUE TITLE
DLL load failed while importing the _ext module

### ISSUE THREAD

**Issue by xxinlei** [TMElyralab/Comfyui-MusePose#19]
Successfully installed the following mmlab packages.
However I encountered another problem.

- mmcv                          2.1.0
- mmdet                         3.2.0
- mmengine                      0.10.4
- mmpose                        1.3.1

I'm not sure what could be causing this issue or how to resolve it :-(

```
2024-06-03 22:16:14,308- root:179- ERROR- !!! Exception during processing!!! DLL load failed while importing _ext: 找不到指定的程序。
2024-06-03 22:16:14,309- root:180- ERROR- Traceback (most recent call last):
  File "D:\User\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 554, in posealign_func
    return run_align_video_with_filterPose_translate_smooth(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 276, in run_align_video_with_filterPose_translate_smooth
    detector = DWposeDetector(
               ^^^^^^^^^^^^^^^
  File "D:\User\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose\pose\script\dwpose.py", line 72, in __init__
    from pose.script.wholebody import Wholebody
  File "D:\User\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose\pose\script\wholebody.py", line 11, in <module>
    from mmdet.apis import inference_detector, init_detector
  File "D:\User\ComfyUI_windows_portable\python_embeded\Lib\site-packages\mmdet\apis\__init__.py", line 2, in <module>
    from .det_inferencer import DetInferencer
  File "D:\User\ComfyUI_windows_portable\python_embeded\Lib\site-packages\mmdet\apis\det_inferencer.py", line 22, in <module>
    from mmdet.evaluation import INSTANCE_OFFSET
  File "D:\User\ComfyUI_windows_portable\python_embeded\Lib\site-packages\mmdet\evaluation\__init__.py", line 4, in <module>
    from .metrics import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\ComfyUI_windows_portable\python_embeded\Lib\site-packages\mmdet\evaluation\metrics\__init__.py", line 5, in <module>
    from .coco_metric import CocoMetric
  File "D:\User\ComfyUI_windows_portable\python_embeded\Lib\site-packages\mmdet\evaluation\metrics\coco_metric.py", line 18, in <module>
    from mmdet.structures.mask import encode_mask_results
  File "D:\User\ComfyUI_windows_portable\python_embeded\Lib\site-packages\mmdet\structures\mask\__init__.py", line 3, in <module>
    from .structures import (BaseInstanceMasks, BitmapMasks, PolygonMasks,
  File "D:\User\ComfyUI_windows_portable\python_embeded\Lib\site-packages\mmdet\structures\mask\structures.py", line 12, in <module>
    from mmcv.ops.roi_align import roi_align
  File "D:\User\ComfyUI_windows_portable\python_embeded\Lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "D:\User\ComfyUI_windows_portable\python_embeded\Lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
                 ^^^^^^^^^^^^^^^^^^^^
  File "D:\User\ComfyUI_windows_portable\python_embeded\Lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
ImportError: DLL load failed while importing _ext: 找不到指定的程序。
```

**Comment by ioritree** [comment]
+cu118 ,py310 不會出現這錯誤
+cu121,py311 會報錯

**Comment by myprivacygithub** [comment]
same error

**Comment by xxinlei** [comment]
> +cu118 ,py310 不會出現這錯誤 +cu121,py311 會報錯

thank you! cu118 + py310 and problem solved
but I got this error
```
ERROR- !!! Exception during processing!!! Error(s) in loading state_dict for CLIPVisionModelWithProjection:
        size mismatch for vision_model.embeddings.class_embedding: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
```

**Comment by xxinlei** [comment]
> same error

whats your pytorch version? 
I reinstall pytorch with cu118 and it works

**Comment by zpengcom** [comment]
torch 2.1.1+cu121,py311 is normal.
torch 2.2.2+cu121,py311 reports the same error.

**Comment by zyd232** [comment]
I solved this problem by reinstalling some packages to make them compatible.

And I found these related packages' versions are compatible: 
```
xformers: 0.0.23
torch: 2.1.1+cu121
torchvision: 0.16.1+cu121
torchaudio: 2.1.1+cu121
mmcv: 2.1.0
mmdet: 3.2.0
mmpose: 1.3.2
```
