### ISSUE TITLE
Problem: name 'init_detector' is not defined

### ISSUE THREAD

**Issue by Affegithub** [TMElyralab/Comfyui-MusePose#2]
Hi, thanks for structuring new nodes, but I got a below error during it runs "muse_pose_allign".
Hope you can give me an advise to solve this error.
Error description was as follows:

Error occurred when executing museposealign:

name 'init_detector' is not defined

File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 554, in posealign_func
return run_align_video_with_filterPose_translate_smooth(args)
File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 276, in run_align_video_with_filterPose_translate_smooth
detector = DWposeDetector(
File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose\pose\script\dwpose.py", line 74, in __init__
self.pose_estimation = Wholebody(det_config, det_ckpt, pose_config, pose_ckpt, device)
File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose\pose\script\wholebody.py", line 51, in __init__
self.detector = init_detector(det_config, det_ckpt, device=device)

**Comment by mrkennypowers** [comment]
I'm having the same issue.

**Comment by lulu-xiao** [comment]
> Hi, thanks for structuring new nodes, but I got a below error during it runs "muse_pose_allign". Hope you can give me an advise to solve this error. Error description was as follows:
> 
> Error occurred when executing museposealign:
> 
> name 'init_detector' is not defined
> 
> File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 554, in posealign_func return run_align_video_with_filterPose_translate_smooth(args) File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 276, in run_align_video_with_filterPose_translate_smooth detector = DWposeDetector( File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose\pose\script\dwpose.py", line 74, in **init** self.pose_estimation = Wholebody(det_config, det_ckpt, pose_config, pose_ckpt, device) File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose\pose\script\wholebody.py", line 51, in **init** self.detector = init_detector(det_config, det_ckpt, device=device)

Has mmdet been successfully installed?
<img width="483" alt="企业微信截图_3fd99e06-4ed1-4254-8a9b-3cd3f2b539a3" src="https://github.com/TMElyralab/Comfyui-MusePose/assets/114042542/d49b6092-2380-4a5e-90c1-96a279d76d03">

**Comment by pondloso** [comment]
I'm also had same error,try to re install "mmcv " 
 "mmdet " "mmpose "  still get same error.

**Comment by meilongggg** [comment]
same error for me too, please help us solve it as soon as possible

**Comment by meilongggg** [comment]
I checked that there indeed is mmdet in site packages in python embedded for comfyui, but it still doesn't work

**Comment by Appolonius001** [comment]
same here
name 'init_detector' is not defined

**Comment by meilongggg** [comment]
where should the mmdet file be located at?

**Comment by SoaringTiger** [comment]
same error

**Comment by fusillustrator** [comment]
same error

**Comment by ioritree** [comment]
same error

**Comment by gstocker75** [comment]
same

**Comment by ariyean** [comment]
same error

**Comment by ManuelMultiverse** [comment]
same error here

**Comment by SirLatore** [comment]
Same error for me also

**Comment by czk32611** [comment]
This error means that `mmcv`, `mmpose` or `mmdet` is not installed correctly. Plz check them again.

**Comment by meilongggg** [comment]
> This error means that `mmcv`, `mmpose` or `mmdet` is not installed correctly. Plz check them again.

how to install these for portable Comfyui ?

**Comment by fusillustrator** [comment]
> This error means that `mmcv`, `mmpose` or `mmdet` is not installed correctly. Plz check them again.

how to install them?

**Comment by chees-cn** [comment]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/root/ComfyUI/custom_nodes/Comfyui-MusePose/nodes.py", line 554, in posealign_func
    return run_align_video_with_filterPose_translate_smooth(args)
  File "/root/ComfyUI/custom_nodes/Comfyui-MusePose/nodes.py", line 276, in run_align_video_with_filterPose_translate_smooth
    detector = DWposeDetector(
  File "/root/ComfyUI/custom_nodes/Comfyui-MusePose/pose/script/dwpose.py", line 74, in __init__
    self.pose_estimation = Wholebody(det_config, det_ckpt, pose_config, pose_ckpt, device)
  File "/root/ComfyUI/custom_nodes/Comfyui-MusePose/pose/script/wholebody.py", line 51, in __init__
    self.detector = init_detector(det_config, det_ckpt, device=device)
NameError: name 'init_detector' is not defined

**Comment by SirLatore** [comment]
the installation of all mmcv , mmpose and mmdet was sucessful just as instructed in the readme file . 

here is the error message :

Error occurred when executing museposealign:

name 'init_detector' is not defined

File "C:\Local\AI\Comfy\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\Local\AI\Comfy\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\Local\AI\Comfy\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\Local\AI\Comfy\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 554, in posealign_func
return run_align_video_with_filterPose_translate_smooth(args)
File "C:\Local\AI\Comfy\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 276, in run_align_video_with_filterPose_translate_smooth
detector = DWposeDetector(
File "C:\Local\AI\Comfy\ComfyUI\custom_nodes\Comfyui-MusePose\pose\script\dwpose.py", line 74, in __init__
self.pose_estimation = Wholebody(det_config, det_ckpt, pose_config, pose_ckpt, device)
File "C:\Local\AI\Comfy\ComfyUI\custom_nodes\Comfyui-MusePose\pose\script\wholebody.py", line 51, in __init__
self.detector = init_detector(det_config, det_ckpt, device=device)

**Comment by rethink-studios** [comment]
(same)

Error occurred when executing museposealign:

name 'init_detector' is not defined

File "D:\COMFYUI_BETA\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\COMFYUI_BETA\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\COMFYUI_BETA\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 554, in posealign_func
return run_align_video_with_filterPose_translate_smooth(args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 276, in run_align_video_with_filterPose_translate_smooth
detector = DWposeDetector(
^^^^^^^^^^^^^^^
File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\Comfyui-MusePose\pose\script\dwpose.py", line 74, in __init__
self.pose_estimation = Wholebody(det_config, det_ckpt, pose_config, pose_ckpt, device)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\Comfyui-MusePose\pose\script\wholebody.py", line 51, in __init__
self.detector = init_detector(det_config, det_ckpt, device=device)
^^^^^^^^^^^^^

**Comment by gstocker75** [comment]
ok i got it working.  pain in the ass big time.  

this is my setup. for portable comfyui on windows 11.  so no guarantee if you don't match 
```
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: D:\AI\2024ComfyUI_windows_portable\python_embeded\python.exe

Total VRAM 24564 MB, total RAM 65382 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
```

assuming you just used powershell or terminal to install things as i did...
first you need to
pip uninstall and or mim uninstall all the mm requirements from powershell or terminal or whatever
 mim UNINSTALL mmengine 
 mim UNINSTALL mmcv
 mim UNINSTALL mmdet
 mim UNINSTALL mmpose
 
 
 now install the mm requirements into your embedded python env. 
` ..\..\..\python_embeded\python.exe -s -m mim install mmengine`
this is a compiled version of mmcv and avoids the building wheel issues...
` ..\..\..\python_embeded\python.exe -s -m mim install --no-cache-dir mmcv==2.2.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.0/index.html`
`..\..\..\python_embeded\python.exe -s -m mim install --no-cache-dir "mmdet>=3.1.0"`
`..\..\..\python_embeded\python.exe -s -m mim install --no-cache-dir "mmpose==1.3.1"`

you may get some errors like mmcv is at version blah blah but mmpose or mmdet requires version blah blah
just look at the last entry of the error with the path to the __init__.py file and go update the <= as needed in those files or just up the maxversion number and save the files. 

restart comfy, you should be good.

**Comment by fusillustrator** [comment]
> ok i got it working. pain in the ass big time.
> 
> this is my setup. for portable comfyui on windows 11. so no guarantee if you don't match
> 
> ```
> ** Platform: Windows
> ** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
> ** Python executable: D:\AI\2024ComfyUI_windows_portable\python_embeded\python.exe
> 
> Total VRAM 24564 MB, total RAM 65382 MB
> pytorch version: 2.3.0+cu121
> xformers version: 0.0.26.post1
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
> VAE dtype: torch.bfloat16
> Using xformers cross attention
> ```
> 
> assuming you just used powershell or terminal to install things as i did... first you need to go to your musepose dir under comfy `ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-MusePose` `git pull` i picked up a couple updated files tonight. pip uninstall and or mim uninstall all the mm requirements from powershell or terminal or whatever mim UNINSTALL mmengine mim UNINSTALL mmcv mim UNINSTALL mmdet mim UNINSTALL mmpose
> 
> now install the mm requirements into your embedded python env. ` ..\..\..\python_embeded\python.exe -s -m mim install mmengine`
> 
> this is a compiled version of mmcv and avoids the building wheel issues... ` ..\..\..\python_embeded\python.exe -s -m mim install --no-cache-dir mmcv==2.2.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.0/index.html`
> 
> `..\..\..\python_embeded\python.exe -s -m mim install --no-cache-dir "mmdet>=3.1.0"`
> 
> `..\..\..\python_embeded\python.exe -s -m mim install --no-cache-dir "mmpose==1.3.1"`
> 
> you may get some errors like mmcv is at version blah blah but mmpose or mmdet requires version blah blah just look at the last entry of the error with the path to the` __init__.py` file and go update the <= as needed in those files or just up the maxversion number and save the files.
> 
> restart comfy, you should be good.

what updated files?

**Comment by gstocker75** [comment]
> what updated files?
Comfyui-MusePose\pose\script\wholebody.py and something else i forget

**Comment by fusillustrator** [comment]
> > what updated files?
> 
> Comfyui-MusePose\pose\script\wholebody.py and something else i forget

what do you mean by install the mm requirements into your embedded python env.?

**Comment by gstocker75** [comment]
> > > what updated files?
> > 
> > 
> > Comfyui-MusePose\pose\script\wholebody.py and something else i forget
> 
> what do you mean by install the mm requirements into your embedded python env.?

copy and paste the new commands i provided that invoke python.exe into terminal or powershell or whatever you're using
you need the full line ala 
`..\..\..\python_embeded\python.exe -s -m mim install mmengine`

might need to do this first, so you have openmim
`..\..\..\python_embeded\python.exe pip install --no-cache-dir -U openmim `

**Comment by fusillustrator** [comment]
do i put this in the powershell of musepose ?

**Comment by fusillustrator** [comment]
> > > > what updated files?
> > > 
> > > 
> > > Comfyui-MusePose\pose\script\wholebody.py and something else i forget
> > 
> > 
> > what do you mean by install the mm requirements into your embedded python env.?
> 
> copy and paste the new commands i provided that invoke python.exe into terminal or powershell or whatever you're using you need the full line ala `..\..\..\python_embeded\python.exe -s -m mim install mmengine`
> 
> might need to do this first, so you have openmim `..\..\..\python_embeded\python.exe pip install --no-cache-dir -U openmim `

do i put that in the powershell of musepose?

**Comment by gstocker75** [comment]
<img width="1049" alt="powershell" src="https://github.com/TMElyralab/Comfyui-MusePose/assets/4672003/860420ad-525c-4ced-aedc-42537a045cf6">

**Comment by fusillustrator** [comment]
![image](https://github.com/TMElyralab/Comfyui-MusePose/assets/56988734/fd0ed609-c97d-4903-84aa-d2f57eecd430)


> <img alt="powershell" width="1049" src="https://private-user-images.githubusercontent.com/4672003/336330723-860420ad-525c-4ced-aedc-42537a045cf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODMwMjgsIm5iZiI6MTcxNzQ4MjcyOCwicGF0aCI6Ii80NjcyMDAzLzMzNjMzMDcyMy04NjA0MjBhZC01MjVjLTRjZWQtYWVkYy00MjUzN2EwNDVjZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDRUMDYzMjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjEzNmMxMDA3YmI1Nzg4NDJiYmM3MGU4NmE5YWUxMjgzNGNiNTU3YWNkMmMyMThjZDRkMDM4OTFhYzE0ZGFkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Z0Yf4hPZ6315Y-6F73udNgjcX2XnXTIc32JczqeUX6Y">

![image](https://github.com/TMElyralab/Comfyui-MusePose/assets/56988734/df6dc8a0-70bf-4f38-88ce-0eb5459632bd)

**Comment by gstocker75** [comment]
oh your missing PIP
try this 
python -m ensurepip --upgrade

**Comment by fusillustrator** [comment]
> oh your missing PIP try this python -m ensurepip --upgrade

![image](https://github.com/TMElyralab/Comfyui-MusePose/assets/56988734/21c10bae-4afa-4299-a545-25771c4d3231)

**Comment by gstocker75** [comment]
make sure pip.exe is in here 
`ComfyUI_windows_portable\python_embeded\Scripts`
make sure it's installed for all users. make sure 
```
AppData\Local\Programs\Python\Python310\ 
AppData\Local\Programs\Python\Python310\Scripts\
```
are in your windows path.  

i dunno beyond that. really outside the scope of this bug thread anyways

**Comment by ManuelMultiverse** [comment]
any solution for non-portable comfyUI install?

**Comment by ioritree** [comment]
> ok i got it working. pain in the ass big time.
```
Total VRAM 24575 MB, total RAM 65469 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
```
..\..\..\python_embeded\python.exe -s -m mim install --no-cache-dir "mmdet>=3.1.0"

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmcv
  Running setup.py clean for mmcv
Failed to build mmcv
ERROR: Could not build wheels for mmcv, which is required to install pyproject.toml-based projects

**Comment by fusillustrator** [comment]
> make sure pip.exe is in here `ComfyUI_windows_portable\python_embeded\Scripts` make sure it's installed for all users. make sure
> 
> ```
> AppData\Local\Programs\Python\Python310\ 
> AppData\Local\Programs\Python\Python310\Scripts\
> ```
> 
> are in your windows path.
> 
> i dunno beyond that. really outside the scope of this bug thread anyways

how do you install python inside musepose? I am so confused

**Comment by ManuelMultiverse** [comment]
I already managed to install all of them, but having the same issue while running workflow: No module named mmcv
PS C:\Users\manue\ComfyMuse\ComfyUI_windows_portable\ComfyUI\custom_nodes> mim list
Package    Version    Source
---------  ---------  -----------------------------------------
mmcv       2.1.0      https://github.com/open-mmlab/mmcv
mmdet      3.2.0      https://github.com/open-mmlab/mmdetection
mmengine   0.10.4     https://github.com/open-mmlab/mmengine
mmpose     1.3.1      https://github.com/open-mmlab/mmpose

**Comment by SirLatore** [comment]
even after the "pain in the ass" Process im getting this No module named 'mmcv'

**Comment by Tophness** [comment]
[Solution](https://github.com/TMElyralab/Comfyui-MusePose/issues/26) @ #26
