### ISSUE TITLE
MMCV==2.2.0 is used but incompatible.

### ISSUE THREAD

**Issue by Aljnk** [TMElyralab/Comfyui-MusePose#24]
[2024-06-05 12:50] Traceback (most recent call last):
  File "..\Portable\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..\Portable\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..\Portable\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..\Portable\ComfyUI\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 554, in posealign_func
    return run_align_video_with_filterPose_translate_smooth(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..\Portable\ComfyUI\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 276, in run_align_video_with_filterPose_translate_smooth
    detector = DWposeDetector(
               ^^^^^^^^^^^^^^^
  File "..\Portable\ComfyUI\ComfyUI\custom_nodes\Comfyui-MusePose\pose\script\dwpose.py", line 72, in __init__
    from pose.script.wholebody import Wholebody
  File "..\Portable\ComfyUI\ComfyUI\custom_nodes\Comfyui-MusePose\pose\script\wholebody.py", line 6, in <module>
    from mmpose.apis import inference_topdown
  File "..\Portable\ComfyUI\python_embeded\Lib\site-packages\mmpose\apis\__init__.py", line 2, in <module>
    from .inference import (collect_multi_frames, inference_bottomup,
  File "..\Portable\ComfyUI\python_embeded\Lib\site-packages\mmpose\apis\inference.py", line 17, in <module>
    from mmpose.models.builder import build_pose_estimator
  File "..\Portable\ComfyUI\python_embeded\Lib\site-packages\mmpose\models\__init__.py", line 8, in <module>
    from .heads import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^
  File "..\Portable\ComfyUI\python_embeded\Lib\site-packages\mmpose\models\heads\__init__.py", line 6, in <module>
    from .hybrid_heads import DEKRHead, RTMOHead, VisPredictHead
  File "..\Portable\ComfyUI\python_embeded\Lib\site-packages\mmpose\models\heads\hybrid_heads\__init__.py", line 3, in <module>
    from .rtmo_head import RTMOHead
  File "..\Portable\ComfyUI\python_embeded\Lib\site-packages\mmpose\models\heads\hybrid_heads\rtmo_head.py", line 9, in <module>
    from mmdet.utils import ConfigType, reduce_mean
  File "..\Portable\ComfyUI\python_embeded\Lib\site-packages\mmdet\__init__.py", line 17, in <module>
    and mmcv_version < digit_version(mmcv_maximum_version)), \
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.

[2024-06-05 12:50] #4 [museposealign]: 1.16s

**Comment by lulu-xiao** [comment]
> [2024-06-05 12:50] Traceback (most recent call last): File "..\Portable\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "..\Portable\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "..\Portable\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "..\Portable\ComfyUI\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 554, in posealign_func return run_align_video_with_filterPose_translate_smooth(args) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "..\Portable\ComfyUI\ComfyUI\custom_nodes\Comfyui-MusePose\nodes.py", line 276, in run_align_video_with_filterPose_translate_smooth detector = DWposeDetector( ^^^^^^^^^^^^^^^ File "..\Portable\ComfyUI\ComfyUI\custom_nodes\Comfyui-MusePose\pose\script\dwpose.py", line 72, in **init** from pose.script.wholebody import Wholebody File "..\Portable\ComfyUI\ComfyUI\custom_nodes\Comfyui-MusePose\pose\script\wholebody.py", line 6, in from mmpose.apis import inference_topdown File "..\Portable\ComfyUI\python_embeded\Lib\site-packages\mmpose\apis__init__.py", line 2, in from .inference import (collect_multi_frames, inference_bottomup, File "..\Portable\ComfyUI\python_embeded\Lib\site-packages\mmpose\apis\inference.py", line 17, in from mmpose.models.builder import build_pose_estimator File "..\Portable\ComfyUI\python_embeded\Lib\site-packages\mmpose\models__init__.py", line 8, in from .heads import * # noqa ^^^^^^^^^^^^^^^^^^^^ File "..\Portable\ComfyUI\python_embeded\Lib\site-packages\mmpose\models\heads__init__.py", line 6, in from .hybrid_heads import DEKRHead, RTMOHead, VisPredictHead File "..\Portable\ComfyUI\python_embeded\Lib\site-packages\mmpose\models\heads\hybrid_heads__init__.py", line 3, in from .rtmo_head import RTMOHead File "..\Portable\ComfyUI\python_embeded\Lib\site-packages\mmpose\models\heads\hybrid_heads\rtmo_head.py", line 9, in from mmdet.utils import ConfigType, reduce_mean File "..\Portable\ComfyUI\python_embeded\Lib\site-packages\mmdet__init__.py", line 17, in and mmcv_version < digit_version(mmcv_maximum_version)), ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AssertionError: MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.
> 
> [2024-06-05 12:50] #4 [museposealign]: 1.16s

mim install "mmcv==2.1.0"

**Comment by Tophness** [comment]
I solved this by editing site-packages\mmdet\_init_.py.
from `mmcv_maximum_version = '2.2.0'` to `mmcv_maximum_version = '2.3.0'`

**Comment by lulu-xiao** [comment]
> I solved this by editing site-packages\mmdet\ _init_.py. from `mmcv_maximum_version = '2.2.0'` to `mmcv_maximum_version = '2.3.0'`
> 
> [Solution](https://github.com/TMElyralab/Comfyui-MusePose/issues/26) @ #26

this works

**Comment by Young-Chin** [comment]
#62 for cuda==11.8, the version torch==2.0.1, mmcv==2.0.1 solved~
