### ISSUE TITLE
Finally installed successfully on Windows, it's really a nightmare

### ISSUE THREAD

**Issue by huiyichanmian** [TMElyralab/Comfyui-MusePose#27]
Let me share my installation process below：
Python version: 3.11.8
cuda : 12.1
Python executable: ComfyUI_windows_portable\python_embeded\python.exe
torch version:  2.1.1+cu121   (Very important)
xformers version: 0.0.23

torch url: https://pytorch.org/get-started/previous-versions/

Torch suggests choosing the same version as me, as the mmcv version requires 2.1.0，Torch 2.2. x and above versions do not have the corresponding mmcv version 2.1.0, which is not provided by the official and needs to be compiled by oneself. Compiling on your own is a bunch of unimaginable problems, so in order to reduce trouble for yourself.

After confirming all the above, you can install the project's dependency packages.

`pip install -r requirements.txt`

If you are using native comfyui, it may prompt a missing aliyunsdk,

`pip install aliyun-python-sdk-core-v3==2.13.10`

Next, install openmim:

 `pip install --no-cache-dir -U openmim `
` mim install mmengine `

Now, please note not to use `mim install "mmcv>=2.0.1"`.Do not use, do not use!

Next, please use the following command to install mmcv:

`pip install mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cu121/torch2.1/index.html`

Official page of mmcv：https://mmcv.readthedocs.io/zh-cn/latest/get_started/installation.html

Continue installing mmdet and mmpose now, please pay attention to the installation sequence.

` mim install "mmdet>=3.1.0" `
` mim install "mmpose>=1.1.0" `

Finally, start comfyui！！！

![image](https://github.com/TMElyralab/Comfyui-MusePose/assets/45684950/37aa09b6-c912-4e20-940b-206f68cda20d)

**Comment by rethink-studios** [comment]
How would this solution work with python_embeded?

**Comment by huiyichanmian** [comment]
> How would this solution work with python_embeded?


Method 1: You can add `ComfyUI_windows_portable \ python_embeded \ pythn.exe` to the system environment variable, so that you can use it directly. However, if you have other versions of Python in your system, I do not recommend doing so.

Method 2: You can directly enter the python_embeded directory and add `pythn.exe - m` before all commands.

When using the mim command, also add `pythn.exe - m` before it.

Note that when installing requirements. txt, please pay attention to the path, or you can copy this file to the current directory and then execute ` pythn.exe - m pip install - r requirements. txt`

**Comment by ioritree** [comment]
thank you ,your method work on +cu121

**Comment by minipuft** [comment]
confirmed as working dindn't mess with any of my 50 custom nodes installed.

**Comment by lulu-xiao** [comment]
#26 can change "mmdet/init.py" line9 "2.2.0" to "2.3.0" to forcely make it compatible

**Comment by huiyichanmian** [comment]
> #26 can change "mmdet/init.py" line9 "2.2.0" to "2.3.0" to forcely make it compatible

If the version is changed, it is easy to encounter a problem where 'Problem: name' init_detector 'is not defined`

**Comment by xxinlei** [comment]
Installed successfully but I keep getting this error..

```
RuntimeError: Error(s) in loading state_dict for CLIPVisionModelWithProjection:
        size mismatch for vision_model.embeddings.class_embedding: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for vision_model.embeddings.patch_embedding.weight: copying a param with shape torch.Size([1024, 3, 14, 14]) from checkpoint, the shape in current model is torch.Size([768, 3, 32, 32]).
        size mismatch for vision_model.embeddings.position_embedding.weight: copying a param with shape torch.Size([257, 1024]) from checkpoint, the shape in current model is torch.Size([50, 768]).
        size mismatch for vision_model.pre_layrnorm.weight: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for vision_model.pre_layrnorm.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for vision_model.encoder.layers.0.self_attn.k_proj.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        ```

**Comment by jaechanjo** [comment]
Linux환경에서 위처럼 설정했는데, 에러가 발생합니다!

!!! Exception during processing !!!
Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/Comfyui-MusePose/nodes.py", line 563, in posealign_func
    return run_align_video_with_filterPose_translate_smooth(args)
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/Comfyui-MusePose/nodes.py", line 285, in run_align_video_with_filterPose_translate_smooth
    detector = DWposeDetector(
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/Comfyui-MusePose_old/pose/script/dwpose.py", line 75, in __init__
    self.pose_estimation = Wholebody(pose_config, pose_ckpt, device)
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/Comfyui-MusePose_old/pose/script/wholebody.py", line 33, in __init__
    self.detector = init_detector(det_config, det_ckpt, device=device)
  File "/usr/local/lib/python3.10/dist-packages/mmdet/apis/inference.py", line 66, in init_detector
    model = MODELS.build(config.model)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'TopdownPoseEstimator is not in the mmdet::model registry. Please check whether the value of `TopdownPoseEstimator` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

**Comment by edwinzeng2005** [comment]
I am using Stability Matrix.
Not sure how to install mmengine using mim.

**Comment by marcusaureliusfun** [comment]
Thank you, this worked for me. I prepended ..\..\..\python_embeded\python.exe -m to all the commands from inside the Musepose custom node directory. I was finally getting things installed.

**Comment by nianchu1** [comment]
3q ,It works. As you say ,torch version: 2.1.1+cu121  is turly important!!!

**Comment by Dawgmastah** [comment]
This guide is now outdated as 
mim install "mmdet>=3.1.0"

Will install a newer incompatible 3.3.0 version, specify manually which to use 

python.exe -m mim install "mmdet==3.2.0"

**Comment by GUEST-1001** [comment]
I tried to run this command.
`D:\ComfyUI_windows_portable\python_embeded\python.exe -m pip install -r requirements.txt`

Then I got this error.

```
Collecting clip@ https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip#sha256=b5842c25da441d6c581b53a5c60e0c2127ebafe0f746f8e15561a006c6c3be6a (from -r requirements.txt (line 19))
  Using cached https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip (4.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Ignoring eva-decord: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Collecting einops==0.4.1 (from -r requirements.txt (line 1))
  Using cached einops-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting imageio==2.33.0 (from -r requirements.txt (line 2))
  Using cached imageio-2.33.0-py3-none-any.whl.metadata (4.9 kB)
Collecting imageio-ffmpeg==0.4.9 (from -r requirements.txt (line 3))
  Using cached imageio_ffmpeg-0.4.9-py3-none-win_amd64.whl.metadata (1.7 kB)
Collecting omegaconf==2.2.3 (from -r requirements.txt (line 4))
  Using cached omegaconf-2.2.3-py3-none-any.whl.metadata (3.9 kB)
Collecting opencv-contrib-python==4.8.1.78 (from -r requirements.txt (line 5))
  Using cached opencv_contrib_python-4.8.1.78-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting opencv-python==4.8.1.78 (from -r requirements.txt (line 6))
  Using cached opencv_python-4.8.1.78-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting scikit-image==0.21.0 (from -r requirements.txt (line 7))
  Using cached scikit_image-0.21.0.tar.gz (22.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\commands\install.py", line 379, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__
    return any(self)
           ^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
                       ^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built
    candidate = func()
                ^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 187, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 233, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in __init__
    super().__init__(
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 159, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 236, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 315, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\utils\misc.py", line 701, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mesonpy
```
I'm not sure, but it seems like the solution will require
`ensurepip --upgrade`
But
```
D:\ComfyUI_windows_portable\python_embeded\python.exe -m ensurepip --upgrade
D:\ComfyUI_windows_portable\python_embeded\python.exe: No module named ensurepip
```
Can anyone help me?

**Comment by GUEST-1001** [comment]
> I tried to run this command. `D:\ComfyUI_windows_portable\python_embeded\python.exe -m pip install -r requirements.txt`
> 
> Then I got this error.
> 
> ```
> Collecting clip@ https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip#sha256=b5842c25da441d6c581b53a5c60e0c2127ebafe0f746f8e15561a006c6c3be6a (from -r requirements.txt (line 19))
>   Using cached https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip (4.3 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... done
> Ignoring eva-decord: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
> Collecting einops==0.4.1 (from -r requirements.txt (line 1))
>   Using cached einops-0.4.1-py3-none-any.whl.metadata (10 kB)
> Collecting imageio==2.33.0 (from -r requirements.txt (line 2))
>   Using cached imageio-2.33.0-py3-none-any.whl.metadata (4.9 kB)
> Collecting imageio-ffmpeg==0.4.9 (from -r requirements.txt (line 3))
>   Using cached imageio_ffmpeg-0.4.9-py3-none-win_amd64.whl.metadata (1.7 kB)
> Collecting omegaconf==2.2.3 (from -r requirements.txt (line 4))
>   Using cached omegaconf-2.2.3-py3-none-any.whl.metadata (3.9 kB)
> Collecting opencv-contrib-python==4.8.1.78 (from -r requirements.txt (line 5))
>   Using cached opencv_contrib_python-4.8.1.78-cp37-abi3-win_amd64.whl.metadata (20 kB)
> Collecting opencv-python==4.8.1.78 (from -r requirements.txt (line 6))
>   Using cached opencv_python-4.8.1.78-cp37-abi3-win_amd64.whl.metadata (20 kB)
> Collecting scikit-image==0.21.0 (from -r requirements.txt (line 7))
>   Using cached scikit_image-0.21.0.tar.gz (22.7 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
> ERROR: Exception:
> Traceback (most recent call last):
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
>     status = _inner_run()
>              ^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
>     return self.run(options, args)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
>     return func(self, options, args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\commands\install.py", line 379, in run
>     requirement_set = resolver.resolve(
>                       ^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
>     result = self._result = resolver.resolve(
>                             ^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
>     state = resolution.resolve(requirements, max_rounds=max_rounds)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
>     self._add_to_criteria(self.state.criteria, r, parent=None)
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
>     if not criterion.candidates:
>            ^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
>     return bool(self._sequence)
>            ^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__
>     return any(self)
>            ^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>
>     return (c for c in iterator if id(c) not in self._incompatible_ids)
>                        ^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built
>     candidate = func()
>                 ^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 187, in _make_candidate_from_link
>     base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
>                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 233, in _make_base_candidate_from_link
>     self._link_candidate_cache[link] = LinkCandidate(
>                                        ^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in __init__
>     super().__init__(
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 159, in __init__
>     self.dist = self._prepare()
>                 ^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 236, in _prepare
>     dist = self._prepare_distribution()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 315, in _prepare_distribution
>     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
>     return self._prepare_linked_requirement(req, parallel_builds)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
>     dist = _get_prepared_distribution(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
>     abstract_dist.prepare_distribution_metadata(
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
>     self._install_build_reqs(finder)
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs
>     build_reqs = self._get_build_requires_wheel()
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
>     return backend.get_requires_for_build_wheel()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\utils\misc.py", line 701, in get_requires_for_build_wheel
>     return super().get_requires_for_build_wheel(config_settings=cs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
>     return self._call_hook('get_requires_for_build_wheel', {
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
>     raise BackendUnavailable(data.get('traceback', ''))
> pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
>     obj = import_module(mod_path)
>           ^^^^^^^^^^^^^^^^^^^^^^^
>   File "importlib\__init__.py", line 90, in import_module
>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'mesonpy
> ```
> 
> I'm not sure, but it seems like the solution will require `ensurepip --upgrade` But
> 
> ```
> D:\ComfyUI_windows_portable\python_embeded\python.exe -m ensurepip --upgrade
> D:\ComfyUI_windows_portable\python_embeded\python.exe: No module named ensurepip
> ```
> 
> Can anyone help me?

I solved the problem now. Thanks a lot.
As I understand it, the latest version of ComfyUI changes the python version, causing some modules to be lost.

**Comment by Daliuq** [comment]
It also useful in linux.
But in huggingface_hub 0.26 ,the cached_download had been remove in package
so we need downgrade it before author update the project
`pip install huggingface_hub==0.25.2
`
